<a href="https://colab.research.google.com/github/NovrianPratama/MachineLearning/blob/main/5_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

Kelebihan dari NumPy:
1. dapat digunakan beberapa operasi matematika
2. operasi nya cepat

In [ ]:
import numpy as np

In [ ]:
from time import process_time

# List vs NumPy

In [ ]:
# menghitung jumlah waktu yang dibutuhkan untuk proses data angka

python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]  # bagian ini yaitu mengambil value dari range dan menambahkan 5

end_time = process_time()

print(end_time - start_time)

0.0011728879999997055


In [ ]:
# menghitung dengan numpy

np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5 # menambah value 5 untuk setiap elemen array

end_time = process_time()

print(end_time - start_time)

0.0013912509999998157


# **Membuat NumPy Array**

In [ ]:
# contoh array List
array_list = [2,3,4,1,2]
print(array_list)
type(array_list)

[2, 3, 4, 1, 2]


list

In [ ]:
numpy1 = np.array([3,4,5,2,5])
print(numpy1) # numpy array tidak memiliki coma pada angka untuk memisahkannya
type(numpy1)

[3 4 5 2 5]


numpy.ndarray

In [ ]:
# membuat dimesi pada array.
a = np.array([3,1,9,5]) # ini merupakan 1 dimensi array
print(a)
a.shape # menampilkan jumlah baris dan kolom
# jika satu dimensi hanya menghasilkan kolom, artinya terdapat 4 kolom outputnya

[3 1 9 5]


(4,)

In [ ]:
# membuat 2 dimensi pada array
arr_2 = np.array([(1,2,4,2),(3,1,9,4)])
print(arr_2)
arr_2.shape # menampilkan jumlah baris dan kolom
# terdapat  2 baris dan 4 kolom

[[1 2 4 2]
 [3 1 9 4]]


(2, 4)

In [ ]:
# menambahkan data type pada array

arr_type = np.array([(2,4,2,6),(4,2,3,2)],dtype=float) # menggati type data, terdapat titik jika menggunakan float
# jumlah array tiap dimensi harus sama tidak boleh dimensi 1 ada 4 kolom dan dimensi 2 ada 3 kolom
print(arr_type)

[[2. 4. 2. 6.]
 [4. 2. 3. 2.]]


# **Initial Placeholders in Numpy Arrays**

In [ ]:
# membuat numpy array dengan angka nol

zero = np.zeros((4,5)) # tulis kurung lagi saat ingin memasukkan jumlah baris dan kolom
print(zero)
zero.shape # menampilkan jumlah baris dan kolom

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


(4, 5)

In [ ]:
arr_one = np.ones((3,5)) # membuat array dengan nilai 1 secara otomatis dengan mamasukkan jumlah baris dan kolom
print(arr_one)
arr_one.shape # menampilkan jumlah baris dan kolom

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


(3, 5)

In [ ]:
arr_full = np.full((3,2),3) # membuat array dengan nilai yang ditentukan secara otomatis
# tulis jumlah baris dan kolom (), baru masukkan angka array yang diinginkan
print(arr_full)
arr_full.shape # menampilkan jumlah baris dan kolom

[[3 3]
 [3 3]
 [3 3]]


(3, 2)

# **Identity Matrix**

In [ ]:
# 1. membuat identity matrix
arr_id = np.eye(5) # memasukkan jumlah baris dan kolom
# eye digunakan untuk membuat array nilai 1 diagonal
print(arr_id)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# membuat random values array
arr_random = np.random.random((2,6)) # memasukkan jumlah baris dan kolom
# fungsi random yaitu membuat angka array acak dengan angka diantara 0 sampai 1
print(arr_random)

[[0.26462062 0.13447727 0.62121971 0.4387305  0.42942875 0.01605336]
 [0.32535662 0.16521486 0.26381038 0.46765595 0.67882054 0.72431475]]


In [ ]:
# membuat random integer values array
# menggunakan randint (random integer)= untuk membuat array random integer
arr_int = np.random.randint(1,20,(4,5))
# parameter randint = (angka terkecil, batas angka terbesar, (baris, kolom))
print(arr_int)

[[ 4  2 18 19 10]
 [ 3  6  8  1 16]
 [17 13  3 13  9]
 [ 4 11 18 13 16]]


# **Array of evenly space values**

In [ ]:
# array of evenly space values -> fokus pada value yang diminta
arr_val = np.linspace(10,30,5) # (start,stop,value)
print(arr_val)
# hasilnya bertipe float, akan fokus pada value yg diminta yaitu 5

[10. 15. 20. 25. 30.]


In [ ]:
# array mengikuti jumlah step
'''
hasil valuenya akan mengikuti step yang diminta
misal mulai dari 5 maka angka setelahnya yaitu 10, karena step/langkah 5
unutk angka selanjutnya adalah 5+5=10
karena batasnya 30 dan langkah akhir 30 maka angka terakhir tidak ditulis 30, itu batasnya
'''
arr_step = np.arange(5,1000,5) # (start,stop,step)
print(arr_step)


[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175 180
 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265 270
 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355 360
 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445 450
 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535 540
 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625 630
 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715 720
 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805 810
 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895 900
 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985 990
 995]


In [ ]:
# list to numpy array

list_con = [3,5,2,6,12]

arr_convert = np.asarray(list_con)
print(arr_convert)
type(arr_convert)

# saat diconvert maka koma diantara angka akan hilang

[ 3  5  2  6 12]


numpy.ndarray

# **Analyst Numpy Array**

In [ ]:
# membuat random integer

arr_value = np.random.randint(10,100,(5,5))
print(arr_value)

[[41 79 71 73 74]
 [17 89 51 81 69]
 [84 67 82 94 31]
 [12 84 14 95 68]
 [84 61 17 60 30]]


In [ ]:
# array of Dimension
print(arr_value.shape)

# ini untuk melihat baris dan kolom pada array atau sebutannya dimensi

(5, 5)


In [ ]:
# number of dimension - >mengacu pada jumlah axes atau tingkat dimensi dalam array
print(arr_value.ndim)

# ini untuk melihat jumlah dimensi pada array

2


In [ ]:
# jumlah elemen pada array
print(arr_value.size)

# ini untuk melihat jumlah elemen pada array
# hasilnya 25 karena memiliki 5 baris dan 5 kolom artinya 5x5

25


In [ ]:
# melihat tipe data array
print(arr_value.dtype)

# int64 = tipe data integer dan 64 artinya bit windows

int64


# **Mathematical Operations On a np array**

In [ ]:
# menggabungkan 2 list tanpa numpy
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)
'''
operasi + harusnya digunakan untuk menambahkan saling menambahkan value masing2 list
tapi penggunaan + menggabungkan 2 list istilahnya concante atau join
'''

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Operasi pada list

In [ ]:
arr_opr1 = np.random.randint(1,10,(4,4))
arr_opr2 = np.random.randint(1,10,(4,4))

print(arr_opr1)
print("\n")
print(arr_opr2)

[[5 8 1 6]
 [9 9 4 7]
 [8 9 7 3]
 [6 5 1 9]]


[[2 2 1 2]
 [6 3 3 4]
 [6 6 8 7]
 [6 2 4 3]]


In [ ]:
# operasi dibawah ini akan digunakan untuk melakukan penjumlahan pada array 1 dan 2
# penjumlahan tiap masing2 index array 1 dan array 2
print("\n tambah")
print(arr_opr1 + arr_opr2)
print("\n kurang")
print(arr_opr1 - arr_opr2)
print("\n kali")
print(arr_opr1 * arr_opr2)
print("\n bagi")
print(arr_opr1 / arr_opr2)


 tambah
[[ 7 10  2  8]
 [15 12  7 11]
 [14 15 15 10]
 [12  7  5 12]]

 kurang
[[ 3  6  0  4]
 [ 3  6  1  3]
 [ 2  3 -1 -4]
 [ 0  3 -3  6]]

 kali
[[10 16  1 12]
 [54 27 12 28]
 [48 54 56 21]
 [36 10  4 27]]

 bagi
[[2.5        4.         1.         3.        ]
 [1.5        3.         1.33333333 1.75      ]
 [1.33333333 1.5        0.875      0.42857143]
 [1.         2.5        0.25       3.        ]]


In [ ]:
# operasi mtk menggunakan np

arr_opr1 = np.random.randint(2,12,(4,4))
arr_opr2 = np.random.randint(1,10,(4,4))

print(arr_opr1)
print("\n")
print(arr_opr2)

[[ 6  2 10  8]
 [ 5  2  2 10]
 [10  3  3  7]
 [10  2 11 10]]


[[6 2 3 7]
 [9 8 4 9]
 [9 6 8 1]
 [6 5 5 6]]


In [ ]:
# pengganti operasi mtk +-*/ , menggunakan numpy

print("\n tambah")
print(np.add(arr_opr1,arr_opr2))
print("\n kurang")
print(np.subtract(arr_opr1,arr_opr2))
print("\n kali")
print(np.multiply(arr_opr1,arr_opr2))
print("\n bagi")
print(np.divide(arr_opr1,arr_opr2))


 tambah
[[12  4 13 15]
 [14 10  6 19]
 [19  9 11  8]
 [16  7 16 16]]

 kurang
[[ 0  0  7  1]
 [-4 -6 -2  1]
 [ 1 -3 -5  6]
 [ 4 -3  6  4]]

 kali
[[36  4 30 56]
 [45 16  8 90]
 [90 18 24  7]
 [60 10 55 60]]

 bagi
[[1.         1.         3.33333333 1.14285714]
 [0.55555556 0.25       0.5        1.11111111]
 [1.11111111 0.5        0.375      7.        ]
 [1.66666667 0.4        2.2        1.66666667]]


# **Array Manipulation**

1. Transpose

In [ ]:
# membuat transpose
arr_tr = np.random.randint(1,10,(3,4))
print(arr_tr)
print(arr_tr.shape)

[[8 3 7 2]
 [3 7 2 5]
 [3 5 7 9]]
(3, 4)


In [ ]:
# cara pertama transpose menggunakan np.transpose
'''
transpose yaitu membalikkan baris menjadi kolom dan kolom menjadi baris
Menggunakan fungsi transpose untuk melakukannya
'''
trans1 = np.transpose(arr_tr)
print(trans1)
print(trans1.shape)

[[8 3 3]
 [3 7 5]
 [7 2 7]
 [2 5 9]]
(4, 3)


In [ ]:
arr_tr = np.random.randint(1,10,(3,4))
print(arr_tr)
print(arr_tr.shape)

[[2 7 6 2]
 [3 6 4 6]
 [2 8 8 1]]
(3, 4)


In [ ]:
# cara kedua transpose menggunakan np.T
trans1 = arr_tr.T
print(trans1)
print(trans1.shape)

[[2 3 2]
 [7 6 8]
 [6 4 8]
 [2 6 1]]
(4, 3)


2. Reshape / mengubah bentuk array

In [ ]:
x = np.random.randint(1,8,(2,3))
print(x)
print(x.shape)

[[4 3 7]
 [7 6 2]]
(2, 3)


In [ ]:
# reshape
'''
Merubah bentuk array kurang lebih sama dengan transpose
masukkan shape baru setelah fungsi reshape (baris, kolom)
'''
y = x.reshape(3,2)
print(y)
print(y.shape)

[[7 6]
 [4 2]
 [3 4]]
(3, 2)
